services:
  # Main prediction system - Cron job for twice daily predictions
  - type: cron
    name: crypto-prediction-system
    env: python3
    plan: free
    runtime: python3
    buildCommand: pip install -r requirements.txt
    schedule: "0 1,13 * * *"  # 1 AM and 1 PM UTC daily (perfect for Asia timezone)
    startCommand: python 6.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TELEGRAM_TEST_BOT_TOKEN
        sync: false
      - key: TELEGRAM_TEST_CHAT_ID
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

databases:
  # PostgreSQL database for persistent storage
  - name: crypto-predictions-db
    plan: free
    databaseName: crypto_predictions
    user: crypto_user

jobs:
  # One-time simple database migration job
  - name: migrate-simple-database
    env: python3
    plan: free
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python migrate_simple_db.py
    envVars:
      - key: DATABASE_URL
        sync: false 