services:
  - type: worker
    name: crypto-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_scheduler.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TZ
        value: Asia/Ho_Chi_Minh
    plan: starter
    region: oregon
    autoDeploy: false 